/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalpage;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class dashboardpage extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashboardpage
     */
    public dashboardpage() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
BasicInternalFrameUI ip = (BasicInternalFrameUI)this.getUI();
ip.setNorthPane(null);
        setSize(800,420);
    }
  Color navcolor = new Color(102,0,255);
    Color headercolor = new Color(51,255,204);
    Color bodycolor = new Color(204,204,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        reports = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        settings = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        manager = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(760, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("best quality product");
        jPanel3.add(jLabel37);
        jLabel37.setBounds(10, 40, 160, 22);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setText("BIKE SHOP PARTRS AND ACCESSORIES");
        jPanel3.add(jLabel38);
        jLabel38.setBounds(10, 10, 370, 22);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 160));

        jPanel11.setBackground(new java.awt.Color(255, 204, 255));
        jPanel11.setLayout(null);

        reports.setBackground(new java.awt.Color(102, 153, 255));
        reports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        reports.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("REPORTS");
        reports.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONSFOLDER/icons8-graph-report-100.png"))); // NOI18N
        reports.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 130));

        jPanel11.add(reports);
        reports.setBounds(300, 40, 190, 160);

        settings.setBackground(new java.awt.Color(102, 153, 255));
        settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsMouseExited(evt);
            }
        });
        settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText(" SETTINGS");
        settings.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONSFOLDER/icons8-settings-100 (3).png"))); // NOI18N
        settings.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 130));

        jPanel11.add(settings);
        settings.setBounds(540, 40, 190, 160);

        manager.setBackground(new java.awt.Color(102, 153, 255));
        manager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                managerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                managerMouseExited(evt);
            }
        });
        manager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("MANAGER USER");
        manager.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONSFOLDER/icons8-user-settings-100.png"))); // NOI18N
        manager.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 130));

        jPanel11.add(manager);
        manager.setBounds(50, 40, 190, 160);

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 160, 830, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerMouseEntered
manager.setBackground(bodycolor);        // TODO add your handling code here:
    }//GEN-LAST:event_managerMouseEntered

    private void managerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerMouseExited
manager.setBackground(navcolor);        // TODO add your handling code here:
    }//GEN-LAST:event_managerMouseExited

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
reports.setBackground(bodycolor)  ;      // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseEntered

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
reports.setBackground(navcolor);        // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseExited

    private void settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseEntered
settings.setBackground(bodycolor);        // TODO add your handling code here:
    }//GEN-LAST:event_settingsMouseEntered

    private void settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseExited
settings.setBackground(navcolor);        // TODO add your handling code here:
    }//GEN-LAST:event_settingsMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel manager;
    private javax.swing.JPanel reports;
    private javax.swing.JPanel settings;
    // End of variables declaration//GEN-END:variables
}
